### ISSUE TITLE
Central server crashes eachother day or so because of invalid postgres connection

### ISSUE THREAD

**Issue by thomasf** [alkasir/alkasir#32]
(An old repository branch is being reintegrated in this code right now so the
problem should disappear with it..)

It's this error, the program should not crash if this happens. It restarts again very fast so it should not be noticeable to users at all but nevertheless it should be fixed.
```go
results, err := clients.DB.GetSamples(uint64(lastID), "")
			if err != nil {
				lg.Fatal(err)
			}
```
            

```log
Log file created at: 2016/02/12 09:05:15
Running on machine: alkasir
Binary: Built with gc go1.5.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0212 09:05:15.852840   26564 analysis.go:26] driver: bad connection
goroutine 593 [running]:
github.com/alkasir/alkasir/vendor/github.com/thomasf/lg.stacks(0xc820070001, 0x0, 0x0, 0x0)
	/home/thomasf/src/github.com/alkasir/alkasir/vendor/github.com/thomasf/lg/glog.go:801 +0xb8
github.com/alkasir/alkasir/vendor/github.com/thomasf/lg.(*loggingT).output(0xe90be0, 0xc800000003, 0xc820116540, 0xe69d95, 0xb, 0x1a, 0x0)
	/home/thomasf/src/github.com/alkasir/alkasir/vendor/github.com/thomasf/lg/glog.go:746 +0x329
github.com/alkasir/alkasir/vendor/github.com/thomasf/lg.(*loggingT).printDepth(0xe90be0, 0x3, 0x1, 0xc8204f3d30, 0x1, 0x1)
	/home/thomasf/src/github.com/alkasir/alkasir/vendor/github.com/thomasf/lg/glog.go:622 +0x1b8
github.com/alkasir/alkasir/vendor/github.com/thomasf/lg.(*loggingT).print(0xe90be0, 0x3, 0xc8204f3d30, 0x1, 0x1)
	/home/thomasf/src/github.com/alkasir/alkasir/vendor/github.com/thomasf/lg/glog.go:613 +0x50
github.com/alkasir/alkasir/vendor/github.com/thomasf/lg.Fatal(0xc8204f3d30, 0x1, 0x1)
	/home/thomasf/src/github.com/alkasir/alkasir/vendor/github.com/thomasf/lg/glog.go:1239 +0x49
github.com/alkasir/alkasir/pkg/central.startAnalysis.func1(0x7f715d831170, 0xc82002a008, 0x7f715d8310c8, 0xc8200728c0, 0x7f715d831198, 0xc82050afb0)
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/analysis.go:26 +0x409
created by github.com/alkasir/alkasir/pkg/central.startAnalysis
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/analysis.go:59 +0x67

goroutine 1 [semacquire, 1758 minutes]:
sync.runtime_Semacquire(0xc82018186c)
	/home/thomasf/.opt/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc820181860)
	/home/thomasf/.opt/go/src/sync/waitgroup.go:126 +0xb4
github.com/alkasir/alkasir/pkg/central.Run()
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/central.go:225 +0x4e1
main.main()
	/home/thomasf/src/github.com/alkasir/alkasir/cmd/alkasir-central/alkasir-central.go:19 +0xa3

goroutine 17 [syscall, 1761 minutes, locked to thread]:
runtime.goexit()
	/home/thomasf/.opt/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 20 [chan receive]:
github.com/alkasir/alkasir/vendor/github.com/thomasf/lg.(*loggingT).flushDaemon(0xe90be0)
	/home/thomasf/src/github.com/alkasir/alkasir/vendor/github.com/thomasf/lg/glog.go:980 +0x67
created by github.com/alkasir/alkasir/vendor/github.com/thomasf/lg.init.1
	/home/thomasf/src/github.com/alkasir/alkasir/vendor/github.com/thomasf/lg/glog.go:379 +0x31f

goroutine 7 [chan receive]:
github.com/alkasir/alkasir/pkg/central/db.init.1.func1()
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/db/sessionstoken.go:102 +0x49
created by github.com/alkasir/alkasir/pkg/central/db.init.1
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/db/sessionstoken.go:105 +0xb3

goroutine 9 [IO wait]:
net.runtime_pollWait(0x7f715c7df690, 0x72, 0xc8200660a0)
	/home/thomasf/.opt/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82005e840, 0x72, 0x0, 0x0)
	/home/thomasf/.opt/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82005e840, 0x0, 0x0)
	/home/thomasf/.opt/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82005e7e0, 0x0, 0x7f715c7e4070, 0xc8200c80a0)
	/home/thomasf/.opt/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8200700f8, 0x452e10, 0x0, 0x0)
	/home/thomasf/.opt/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc8200700f8, 0x0, 0x0, 0x0, 0x0)
	/home/thomasf/.opt/go/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc820064ae0, 0x7f715c7e4038, 0xc8200700f8, 0x0, 0x0)
	/home/thomasf/.opt/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc820064ae0, 0x0, 0x0)
	/home/thomasf/.opt/go/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0xc820010104, 0xe, 0x0, 0x0, 0x0, 0x0)
	/home/thomasf/.opt/go/src/net/http/server.go:1967 +0x8f
github.com/alkasir/alkasir/pkg/central.startMonitoring(0xc820010104, 0xe)
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/central.go:283 +0x22f
created by github.com/alkasir/alkasir/pkg/central.Run
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/central.go:110 +0x6e

goroutine 22 [syscall, 1761 minutes]:
os/signal.loop()
	/home/thomasf/.opt/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/home/thomasf/.opt/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 23 [chan receive, 1761 minutes]:
database/sql.(*DB).connectionOpener(0xc8201c41e0)
	/home/thomasf/.opt/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/home/thomasf/.opt/go/src/database/sql/sql.go:481 +0x336

goroutine 590 [chan receive, 1758 minutes]:
github.com/alkasir/alkasir/pkg/central.Run.func5(0xc820181860)
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/central.go:172 +0x162
created by github.com/alkasir/alkasir/pkg/central.Run
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/central.go:174 +0x193

goroutine 24 [chan receive, 1 minutes]:
github.com/alkasir/alkasir/pkg/shared.GetPublicIPAddr.func1.1(0xc820246180)
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/shared/publicip.go:101 +0xb7c
created by github.com/alkasir/alkasir/pkg/shared.GetPublicIPAddr.func1
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/shared/publicip.go:105 +0x12a

goroutine 604 [select, 1758 minutes, locked to thread]:
runtime.gopark(0xc3e458, 0xc82004af28, 0xb1be88, 0x6, 0x4cd618, 0x2)
	/home/thomasf/.opt/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82004af28, 0x0, 0x18)
	/home/thomasf/.opt/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82004af28)
	/home/thomasf/.opt/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/home/thomasf/.opt/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/home/thomasf/.opt/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 35 [chan receive]:
github.com/alkasir/alkasir/pkg/central.startMonitoring.func1(0x7f715d81c6e0, 0xc820063000)
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/central.go:275 +0x65
created by github.com/alkasir/alkasir/pkg/central.startMonitoring
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/central.go:282 +0x205

goroutine 592 [IO wait, 1758 minutes]:
net.runtime_pollWait(0x7f715c7df090, 0x72, 0xc8200660a0)
	/home/thomasf/.opt/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820168a00, 0x72, 0x0, 0x0)
	/home/thomasf/.opt/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820168a00, 0x0, 0x0)
	/home/thomasf/.opt/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8201689a0, 0x0, 0x7f715c7e4070, 0xc8200de800)
	/home/thomasf/.opt/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820070050, 0xc8202fbc40, 0x0, 0x0)
	/home/thomasf/.opt/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc820070050, 0x0, 0x0, 0x0, 0x0)
	/home/thomasf/.opt/go/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc820349380, 0x7f715c7e4038, 0xc820070050, 0x0, 0x0)
	/home/thomasf/.opt/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc820349380, 0x0, 0x0)
	/home/thomasf/.opt/go/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0xc8200100a6, 0xe, 0x7f715d8291f8, 0xc8206f8270, 0x0, 0x0)
	/home/thomasf/.opt/go/src/net/http/server.go:1967 +0x8f
github.com/alkasir/alkasir/pkg/central.Run.func7(0xc8200100a6, 0xe, 0x7f715d831170, 0xc82002a008, 0x7f715d8310c8, 0xc8200728c0, 0x7f715d831198, 0xc82050afb0)
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/central.go:216 +0x7ae
created by github.com/alkasir/alkasir/pkg/central.Run
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/central.go:220 +0x42c

goroutine 601 [chan receive, 1758 minutes]:
github.com/alkasir/alkasir/pkg/central.startMeasurer.func1(0x7f715d831170, 0xc82002a008, 0x7f715d8310c8, 0xc8200728c0, 0x7f715d831198, 0xc82050afb0)
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/measurements.go:71 +0x37b
created by github.com/alkasir/alkasir/pkg/central.startMeasurer
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/measurements.go:114 +0x74

goroutine 602 [chan receive, 1758 minutes]:
github.com/alkasir/alkasir/pkg/central.startMeasurer.func1(0x7f715d831170, 0xc82002a008, 0x7f715d8310c8, 0xc8200728c0, 0x7f715d831198, 0xc82050afb0)
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/measurements.go:71 +0x37b
created by github.com/alkasir/alkasir/pkg/central.startMeasurer
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/measurements.go:114 +0x74

goroutine 596 [chan receive, 411 minutes]:
github.com/alkasir/alkasir/pkg/central.startMeasurer.func1(0x7f715d831170, 0xc82002a008, 0x7f715d8310c8, 0xc8200728c0, 0x7f715d831198, 0xc82050afb0)
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/measurements.go:71 +0x37b
created by github.com/alkasir/alkasir/pkg/central.startMeasurer
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/measurements.go:114 +0x74

goroutine 605 [chan receive, 8 minutes]:
github.com/alkasir/alkasir/pkg/central.GetHosts.func1(0xc8203c4140)
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/api.go:110 +0x67
created by github.com/alkasir/alkasir/pkg/central.GetHosts
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/api.go:113 +0xf5

goroutine 600 [chan receive, 1758 minutes]:
github.com/alkasir/alkasir/pkg/central.startMeasurer.func1(0x7f715d831170, 0xc82002a008, 0x7f715d8310c8, 0xc8200728c0, 0x7f715d831198, 0xc82050afb0)
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/measurements.go:71 +0x37b
created by github.com/alkasir/alkasir/pkg/central.startMeasurer
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/measurements.go:114 +0x74

goroutine 599 [chan receive, 1758 minutes]:
github.com/alkasir/alkasir/pkg/central.startMeasurer.func1(0x7f715d831170, 0xc82002a008, 0x7f715d8310c8, 0xc8200728c0, 0x7f715d831198, 0xc82050afb0)
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/measurements.go:71 +0x37b
created by github.com/alkasir/alkasir/pkg/central.startMeasurer
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/measurements.go:114 +0x74

goroutine 603 [chan receive, 1758 minutes]:
github.com/alkasir/alkasir/pkg/central.startMeasurer.func1(0x7f715d831170, 0xc82002a008, 0x7f715d8310c8, 0xc8200728c0, 0x7f715d831198, 0xc82050afb0)
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/measurements.go:71 +0x37b
created by github.com/alkasir/alkasir/pkg/central.startMeasurer
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/measurements.go:114 +0x74

goroutine 591 [IO wait, 366 minutes]:
net.runtime_pollWait(0x7f715c7defd0, 0x72, 0xc8200660a0)
	/home/thomasf/.opt/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8202d8bc0, 0x72, 0x0, 0x0)
	/home/thomasf/.opt/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202d8bc0, 0x0, 0x0)
	/home/thomasf/.opt/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8202d8b60, 0x0, 0x7f715c7e4070, 0xc8202da700)
	/home/thomasf/.opt/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc82002a0d0, 0x452e10, 0x0, 0x0)
	/home/thomasf/.opt/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc82002a0d0, 0x0, 0x0, 0x0, 0x0)
	/home/thomasf/.opt/go/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc8200655c0, 0x7f715c7e4038, 0xc82002a0d0, 0x0, 0x0)
	/home/thomasf/.opt/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc8200655c0, 0x0, 0x0)
	/home/thomasf/.opt/go/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0xc82000a0b0, 0xe, 0x7f715d8291f8, 0xc8200d69f0, 0x0, 0x0)
	/home/thomasf/.opt/go/src/net/http/server.go:1967 +0x8f
github.com/alkasir/alkasir/pkg/central.Run.func6(0xc82000a0b0, 0xe, 0x7f715d831170, 0xc82002a008, 0x7f715d8310c8, 0xc8200728c0, 0x7f715d831198, 0xc82050afb0)
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/central.go:189 +0x258
created by github.com/alkasir/alkasir/pkg/central.Run
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/central.go:193 +0x3ac

goroutine 595 [chan receive, 1758 minutes]:
github.com/alkasir/alkasir/pkg/central.startMeasurer.func1(0x7f715d831170, 0xc82002a008, 0x7f715d8310c8, 0xc8200728c0, 0x7f715d831198, 0xc82050afb0)
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/measurements.go:71 +0x37b
created by github.com/alkasir/alkasir/pkg/central.startMeasurer
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/measurements.go:114 +0x74

goroutine 594 [chan receive, 1758 minutes]:
github.com/alkasir/alkasir/pkg/central.startMeasurer.func1(0x7f715d831170, 0xc82002a008, 0x7f715d8310c8, 0xc8200728c0, 0x7f715d831198, 0xc82050afb0)
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/measurements.go:71 +0x37b
created by github.com/alkasir/alkasir/pkg/central.startMeasurer
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/measurements.go:114 +0x74

goroutine 597 [chan receive, 1758 minutes]:
github.com/alkasir/alkasir/pkg/central.startMeasurer.func1(0x7f715d831170, 0xc82002a008, 0x7f715d8310c8, 0xc8200728c0, 0x7f715d831198, 0xc82050afb0)
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/measurements.go:71 +0x37b
created by github.com/alkasir/alkasir/pkg/central.startMeasurer
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/measurements.go:114 +0x74

goroutine 598 [chan receive, 1010 minutes]:
github.com/alkasir/alkasir/pkg/central.startMeasurer.func1(0x7f715d831170, 0xc82002a008, 0x7f715d8310c8, 0xc8200728c0, 0x7f715d831198, 0xc82050afb0)
	/home/thomasf/src/github.com/alkasir/alkasir/pkg/central/measurements.go:71 +0x37b
created by github.com/alkasir/alkasir/pkg/central.startMeasurer
	/home/thomasf/src/github.com /alkasir/alkasir/pkg/central/measurements.go:114 +0x74

```

**Comment by thomasf** [comment]
There is an `sql.ErrBadConn` that can be checked for this problem to do graceful retries.
I have not noticed this error when load testing the api functions.. 

This query is called every 10th second so the error happens about 1/17000 (3600*48/10) calls right now.
